import type { CombatLimits, WeaponConfig } from './WeaponConfig';

export const COMBAT_CONFIG_VERSION = 1;

export const COMBAT_LIMITS = {
	maxPlayers: 4,
	maxWeaponsPerPlayer: 3,
	maxWeaponLevel: 40,
	maxFinalAttackRate: 8,
	maxProjectilesPerPlayer: 32,
	maxCombatEntitiesPerRoom: 128,
	maxImpactEventsPerTick: 256,
	maxCatchupAttacksPerTick: 4,
	maxEntityLifetimeS: 10,
} as const satisfies CombatLimits;

const FULL_AFFINITY = {
	damage: 1,
	attackRate: 1,
	range: 1,
	size: 1,
} as const;

export const WEAPON_CONFIGS = [
	{
		kind: 'aura',
		behavior: 'aura',
		maxLevel: 40,
		baseDamage: 5,
		baseAttackRate: 1,
		baseRadius: 6,
		baseHeight: 3,
		maxActiveEntities: 1,
		bonusAffinity: { ...FULL_AFFINITY, attackRate: 0.8 },
	},
	{
		kind: 'sword',
		behavior: 'sector',
		maxLevel: 40,
		baseDamage: 18,
		baseAttackRate: 1.25,
		baseRange: 11.25,
		baseKnockback: 4,
		totalAngleDegrees: 180,
		targetHitboxRadius: 0.75,
		effectLifetimeS: 0.25,
		hitboxHeight: 2.4,
		maxActiveEntities: 2,
		bonusAffinity: { ...FULL_AFFINITY, range: 0.65 },
	},
	{
		kind: 'axe',
		behavior: 'stationary-projectile',
		maxLevel: 40,
		baseDamage: 12,
		baseAttackRate: 0.25,
		baseProjectileSpeed: 14,
		baseTravelDistance: 8,
		// Le pivot du GLB est decentre vers le manche. A l'echelle visuelle 2,
		// l'extremite opposee balaie environ 3.1 unites autour de ce pivot.
		baseContactRadius: 3.15,
		baseContactHeight: 0.6,
		damageIntervalS: 0.5,
		baseActiveDurationS: 3,
		maxActiveEntities: 2,
		bonusAffinity: { ...FULL_AFFINITY, attackRate: 0.5, size: 1.25 },
	},
	{
		kind: 'staff',
		behavior: 'targeted-projectile',
		maxLevel: 40,
		baseDamage: 24,
		baseAttackRate: 0.65,
		baseAcquisitionRange: 30,
		baseProjectileSpeed: 18,
		maxTurnRateDegreesS: 240,
		collisionRadius: 0.65,
		maxLifetimeS: 3,
		penetration: 0,
		maxActiveEntities: 4,
		bonusAffinity: { ...FULL_AFFINITY, range: 1.25 },
	},
	{
		kind: 'bow',
		behavior: 'spread-projectile',
		maxLevel: 40,
		baseDamage: 10,
		baseAttackRate: 1,
		projectileCount: 3,
		spreadAnglesDegrees: [-45, 0, 45],
		baseProjectileSpeed: 28,
		collisionRadius: 0.25,
		hitboxWidth: 0.25,
		hitboxHeight: 0.25,
		hitboxDepth: 1.2,
		maxLifetimeS: 1.5,
		penetration: 0,
		maxActiveEntities: 12,
		bonusAffinity: { ...FULL_AFFINITY, damage: 0.8, attackRate: 1.2 },
	},
] as const satisfies readonly WeaponConfig[];
